/* Per-item sprite tuning. Every item references one size group;
   groups are the single source of truth for size + dx/dy. */
import { Dimensions } from "react-native";

// scale sizes proportionally to screen width (design base: 390pt)
const SCALE = Dimensions.get("window").width / 390;

type Tuning = { size: number; dx: number; dy: number };

const XS: Tuning = { size: 48, dx: 0, dy: 10 };
const S: Tuning = { size: 60, dx: 0, dy: 5 };
const M: Tuning = { size: 72, dx: 0, dy: -3 };
const L: Tuning = { size: 100, dx: 0, dy: -18 };
const XL: Tuning = { size: 160, dx: 0, dy: -32 };

export const DEFAULT_SIZE = M.size;
export const SPRITE_TUNING: Record<string, Tuning> = {
  "candy-wrapper": XS,
  "cig-butt": XS,
  "cig-butts": XS,
  "paper-clips": XS,
  straw: XS,
  "tea-bag": XS,
  "ttc-transfer": XS,
  "streetcar-token": XS,
  "plant-tag": XS,
  ribbon: XS,
  banana: S,
  apple: S,
  eggshells: S,
  "coffee-grounds": S,
  acorn: S,
  "chestnut-shells": S,
  "pine-needles": S,
  "daffodil-stems": S,
  "seed-packet": S,
  "broken-pen": S,
  razor: S,
  "jam-jar": S,
  "coffeecrisp-wrap": S,
  "teacake-wrap": S,
  "crisp-packet": S,
  "ketchup-chips": S,
  "film-wrap": S,
  napkin: S,
  "candy-wrappers": S,
  "coffee-cup": S,
  leaves: M,
  "glass-jar": M,
  "alu-can": M,
  "office-paper": M,
  "tin-can": M,
  "foam-cup": M,
  "chip-bag": M,
  "aluminum-foil": M,
  "pizza-box": M,
  "corn-husks": M,
  bouquet: M,
  "pumpkin-rind": M,
  "coffee-filter": M,
  chopsticks: M,
  "spray-bottle": M,
  "junk-mail": M,
  "yogurt-tub": M,
  "detergent-bottle": M,
  "cereal-box": M,
  "wine-bottle": M,
  "soup-can": M,
  "grocery-bag": M,
  "plant-pot": M,
  "egg-carton": M,
  "coffee-bag": M,
  clamshell: M,
  "black-tray": M,
  headphones: M,
  "voodoo-box": M,
  "pla-container": M,
  "wet-news": M,
  "pack-rings": M,
  "bike-tube": M,
  "yard-debris": M,
  "pumpkin-pie": M,
  "mini-gourd": M,
  "mini-gourd-1": M,
  "halloween-mask": M,
  "halloween-mask-1": M,
  "fake-web": M,
  "cracked-bucket": M,
  "turkey-bone": M,
  "dead-mums": M,
  "holiday-card": M,
  "gift-wrap": M,
  "broken-ornament": M,
  "string-lights": M,
  "wrap-tube": M,
  "eggnog-carton": M,
  "double-double": M,
  "maple-bottle": M,
  "poutine-box": M,
  "hockey-tape": M,
  bagel: M,
  "peameal-pack": M,
  toque: M,
  "pickle-jar": M,
  "buttertart-box": M,
  flyers: M,
  "milk-bag": M,
  "produce-bag": M,
  "snow-globe": M,
  "raccoon-lid": M,
  "beans-tin": M,
  "milk-bottle-uk": M,
  broadsheet: M,
  "chippy-box": M,
  "biscuit-tin": M,
  welly: M,
  "carrier-bag": M,
  "egg-box-uk": M,
  "flat-cap": M,
  "roast-scraps": M,
  "crisp-tube": M,
  brolly: M,
  "parcel-box": M,
  "tea-tin": M,
  "soil-bag": M,
  "broken-trowel": M,
  "fertilizer-bag": M,
  "spring-flyer": M,
  "easter-grass": M,
  "cracked-pot": M,
  "popsicle-stick": M,
  "sunscreen-bottle": M,
  "ice-cream-tub": M,
  "paper-plate": M,
  "solo-cup": M,
  "glow-stick": M,
  "wax-paper": M,
  "pool-noodle": M,
  "candle-tin": M,
  bottle: M,
  "bottle-red": M,
  "pumpkin-guts": M,
  growler: M,
  "rain-boot": M,
  umbrella: L,
  "sixpack-carrier": L,
  newspaper: L,
  "wet-newspaper": L,
  "aluminum-pie-tin": L,
  "cider-jug": L,
  "cardboard-box": L,
  "broken-rake": XL,
};
export function spriteTuningFor(id: string) {
  const t = SPRITE_TUNING[id] ?? { size: DEFAULT_SIZE, dx: 0, dy: 0 };
  return { size: t.size * SCALE, dx: t.dx * SCALE, dy: t.dy * SCALE };
}
export function spriteSizeFor(id: string): number {
  return spriteTuningFor(id).size;
}
