/* Per-item sprite tuning: size (pt), dx/dy (px offset from centered) */
import { Dimensions } from "react-native";

// scale sizes proportionally to screen width (design base: 390pt)
const SCALE = Dimensions.get("window").width / 390;

export const DEFAULT_SIZE = 72;
export const SPRITE_TUNING: Record<
  string,
  { size: number; dx: number; dy: number }
> = {
  // ── universal ──
  banana: { size: 72, dx: 0, dy: 0 },
  apple: { size: 72, dx: 0, dy: 0 },
  eggshells: { size: 72, dx: 0, dy: 0 },
  "coffee-grounds": { size: 72, dx: 0, dy: 0 },
  leaves: { size: 72, dx: 0, dy: 0 },
  newspaper: { size: 125, dx: 0, dy: -25 },
  "cardboard-box": { size: 72, dx: 0, dy: 0 },
  "glass-jar": { size: 72, dx: 0, dy: 0 },
  "alu-can": { size: 72, dx: 0, dy: 0 },
  "office-paper": { size: 72, dx: 0, dy: 0 },
  "tin-can": { size: 72, dx: 0, dy: 0 },
  "foam-cup": { size: 72, dx: 0, dy: 0 },
  "chip-bag": { size: 72, dx: 0, dy: 0 },
  "cig-butt": { size: 72, dx: 0, dy: 0 },
  "cig-butts": { size: 72, dx: 0, dy: 0 },
  "broken-pen": { size: 72, dx: 0, dy: 0 },
  "aluminum-foil": { size: 72, dx: 0, dy: 0 },
  "paper-clips": { size: 72, dx: 0, dy: 0 },
  // ── portland ──
  "pizza-box": { size: 72, dx: 0, dy: 0 },
  "yard-debris": { size: 72, dx: 0, dy: 0 },
  "corn-husks": { size: 72, dx: 0, dy: 0 },
  bouquet: { size: 72, dx: 0, dy: 0 },
  "pumpkin-rind": { size: 72, dx: 0, dy: 0 },
  "coffee-filter": { size: 72, dx: 0, dy: 0 },
  napkin: { size: 72, dx: 0, dy: 0 },
  chopsticks: { size: 72, dx: 0, dy: 0 },
  "spray-bottle": { size: 72, dx: 0, dy: 0 },
  growler: { size: 72, dx: 0, dy: 0 },
  "sixpack-carrier": { size: 72, dx: 0, dy: 0 },
  "junk-mail": { size: 72, dx: 0, dy: 0 },
  "yogurt-tub": { size: 72, dx: 0, dy: 0 },
  "detergent-bottle": { size: 72, dx: 0, dy: 0 },
  "cereal-box": { size: 72, dx: 0, dy: 0 },
  "wine-bottle": { size: 72, dx: 0, dy: 0 },
  "soup-can": { size: 72, dx: 0, dy: 0 },
  "grocery-bag": { size: 72, dx: 0, dy: 0 },
  "plant-pot": { size: 72, dx: 0, dy: 0 },
  "egg-carton": { size: 72, dx: 0, dy: 0 },
  "coffee-bag": { size: 72, dx: 0, dy: 0 },
  clamshell: { size: 72, dx: 0, dy: 0 },
  umbrella: { size: 72, dx: 0, dy: 0 },
  "black-tray": { size: 72, dx: 0, dy: 0 },
  "film-wrap": { size: 72, dx: 0, dy: 0 },
  "rain-boot": { size: 72, dx: 0, dy: 0 },
  razor: { size: 72, dx: 0, dy: 0 },
  straw: { size: 72, dx: 0, dy: 0 },
  "candy-wrapper": { size: 72, dx: 0, dy: 0 },
  headphones: { size: 72, dx: 0, dy: 0 },
  bottle: { size: 90, dx: 0, dy: -18 },
  "bottle-red": { size: 90, dx: 0, dy: -18 },
  "coffee-cup": { size: 72, dx: 0, dy: 0 },
  "voodoo-box": { size: 72, dx: 0, dy: 0 },
  "pla-container": { size: 72, dx: 0, dy: 0 },
  "wet-news": { size: 72, dx: 0, dy: 0 },
  "pack-rings": { size: 72, dx: 0, dy: 0 },
  "bike-tube": { size: 72, dx: 0, dy: 0 },
  // ── toronto ──
  "double-double": { size: 72, dx: 0, dy: 0 },
  "maple-bottle": { size: 72, dx: 0, dy: 0 },
  "ttc-transfer": { size: 72, dx: 0, dy: 0 },
  "poutine-box": { size: 72, dx: 0, dy: 0 },
  "hockey-tape": { size: 72, dx: 0, dy: 0 },
  bagel: { size: 72, dx: 0, dy: 0 },
  "peameal-pack": { size: 72, dx: 0, dy: 0 },
  "coffeecrisp-wrap": { size: 72, dx: 0, dy: 0 },
  "ketchup-chips": { size: 72, dx: 0, dy: 0 },
  toque: { size: 72, dx: 0, dy: 0 },
  "pickle-jar": { size: 72, dx: 0, dy: 0 },
  "buttertart-box": { size: 72, dx: 0, dy: 0 },
  flyers: { size: 72, dx: 0, dy: 0 },
  "milk-bag": { size: 72, dx: 0, dy: 0 },
  "produce-bag": { size: 72, dx: 0, dy: 0 },
  "snow-globe": { size: 72, dx: 0, dy: 0 },
  "raccoon-lid": { size: 72, dx: 0, dy: 0 },
  "streetcar-token": { size: 72, dx: 0, dy: 0 },
  // ── uk ──
  "tea-bag": { size: 72, dx: 0, dy: 0 },
  "crisp-packet": { size: 72, dx: 0, dy: 0 },
  "beans-tin": { size: 72, dx: 0, dy: 0 },
  "milk-bottle-uk": { size: 72, dx: 0, dy: 0 },
  broadsheet: { size: 72, dx: 0, dy: 0 },
  "chippy-box": { size: 72, dx: 0, dy: 0 },
  "biscuit-tin": { size: 72, dx: 0, dy: 0 },
  welly: { size: 72, dx: 0, dy: 0 },
  "carrier-bag": { size: 72, dx: 0, dy: 0 },
  "egg-box-uk": { size: 72, dx: 0, dy: 0 },
  "jam-jar": { size: 72, dx: 0, dy: 0 },
  "teacake-wrap": { size: 72, dx: 0, dy: 0 },
  "flat-cap": { size: 72, dx: 0, dy: 0 },
  "roast-scraps": { size: 72, dx: 0, dy: 0 },
  "crisp-tube": { size: 72, dx: 0, dy: 0 },
  brolly: { size: 72, dx: 0, dy: 0 },
  "parcel-box": { size: 72, dx: 0, dy: 0 },
  "tea-tin": { size: 72, dx: 0, dy: 0 },
  // ── spring ──
  "daffodil-stems": { size: 72, dx: 0, dy: 0 },
  "seed-packet": { size: 72, dx: 0, dy: 0 },
  "plant-tag": { size: 72, dx: 0, dy: 0 },
  "soil-bag": { size: 72, dx: 0, dy: 0 },
  "broken-trowel": { size: 72, dx: 0, dy: 0 },
  "fertilizer-bag": { size: 72, dx: 0, dy: 0 },
  "spring-flyer": { size: 72, dx: 0, dy: 0 },
  "easter-grass": { size: 72, dx: 0, dy: 0 },
  "cracked-pot": { size: 72, dx: 0, dy: 0 },
  // ── summer ──
  "popsicle-stick": { size: 72, dx: 0, dy: 0 },
  "sunscreen-bottle": { size: 72, dx: 0, dy: 0 },
  "ice-cream-tub": { size: 72, dx: 0, dy: 0 },
  "paper-plate": { size: 72, dx: 0, dy: 0 },
  "solo-cup": { size: 72, dx: 0, dy: 0 },
  "glow-stick": { size: 72, dx: 0, dy: 0 },
  "wax-paper": { size: 72, dx: 0, dy: 0 },
  "pool-noodle": { size: 72, dx: 0, dy: 0 },
  "candle-tin": { size: 72, dx: 0, dy: 0 },
  // ── fall ──
  acorn: { size: 72, dx: 0, dy: 0 },
  "pumpkin-guts": { size: 90, dx: 0, dy: -10 },
  "pumpkin-pie": { size: 72, dx: 0, dy: 0 },
  "mini-gourd": { size: 72, dx: 0, dy: 0 },
  "candy-wrappers": { size: 72, dx: 0, dy: 0 },
  "halloween-mask": { size: 81, dx: 0, dy: 1 },
  "cider-jug": { size: 115, dx: 0, dy: -32 },
  "mini-gourd-1": { size: 80, dx: 0, dy: -8 },
  "halloween-mask-1": { size: 81, dx: 0, dy: 1 },
  "fake-web": { size: 72, dx: 0, dy: 0 },
  "aluminum-pie-tin": { size: 125, dx: 0, dy: -35 },
  "cracked-bucket": { size: 72, dx: 0, dy: 0 },
  "broken-rake": { size: 175, dx: 0, dy: -45 },
  "turkey-bone": { size: 72, dx: 0, dy: 0 },
  "dead-mums": { size: 72, dx: 0, dy: 0 },
  // ── winter ──
  "pine-needles": { size: 72, dx: 0, dy: 0 },
  "holiday-card": { size: 72, dx: 0, dy: 0 },
  "chestnut-shells": { size: 72, dx: 0, dy: 0 },
  "wrap-tube": { size: 72, dx: 0, dy: 0 },
  "gift-wrap": { size: 72, dx: 0, dy: 0 },
  ribbon: { size: 72, dx: 0, dy: 0 },
  "eggnog-carton": { size: 72, dx: 0, dy: 0 },
  "broken-ornament": { size: 72, dx: 0, dy: 0 },
  "string-lights": { size: 72, dx: 0, dy: 0 },
};
export function spriteTuningFor(id: string) {
  const t = SPRITE_TUNING[id] ?? { size: DEFAULT_SIZE, dx: 0, dy: 0 };
  return { size: t.size * SCALE, dx: t.dx * SCALE, dy: t.dy * SCALE };
}
export function spriteSizeFor(id: string): number {
  return spriteTuningFor(id).size;
}
